// Package receipt builds a one-page rent receipt PDF using only the standard
// library (no external PDF dependency).
//
// The built-in Helvetica font only covers Latin characters, so any other
// character (e.g. Hindi names, the rupee sign) is written as "?" / "Rs.".
package receipt

import (
	"bytes"
	"fmt"
	"strings"
)

type Data struct {
	ReceiptNo     string
	PropertyTitle string
	TenantName    string
	OwnerName     string
	PeriodLabel   string // e.g. "October 2026"
	DueDate       string
	PaidDate      string
	Method        string
	Reference     string
	RentAmount    float64
	LateFee       float64
	LateDays      int
	Total         float64
}

func clean(s string, max int) string {
	s = strings.ReplaceAll(s, "₹", "Rs. ")
	var b strings.Builder
	for _, r := range s {
		switch {
		case r == '\n' || r == '\r' || r == '\t':
			b.WriteByte(' ')
		case r >= 32 && r < 127:
			b.WriteRune(r)
		default:
			b.WriteByte('?')
		}
	}
	out := strings.TrimSpace(b.String())
	if len(out) > max {
		out = out[:max-3] + "..."
	}
	return out
}

func esc(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `(`, `\(`)
	s = strings.ReplaceAll(s, `)`, `\)`)
	return s
}

func money(v float64) string { return fmt.Sprintf("Rs. %.2f", v) }

// Build returns the PDF bytes.
func Build(d Data) []byte {
	var c bytes.Buffer

	text := func(font string, size int, x, y int, s string) {
		fmt.Fprintf(&c, "BT /%s %d Tf %d %d Td (%s) Tj ET\n", font, size, x, y, esc(s))
	}
	line := func(x1, y1, x2, y2 int) {
		fmt.Fprintf(&c, "0.85 0.88 0.92 RG 0.8 w %d %d m %d %d l S\n", x1, y1, x2, y2)
	}

	// Header band
	c.WriteString("0.082 0.333 0.541 rg 0 742 595 100 re f\n")
	c.WriteString("1 1 1 rg\n")
	text("F2", 24, 50, 790, "RENT RECEIPT")
	text("F1", 11, 50, 766, "Receipt No: "+clean(d.ReceiptNo, 40))
	c.WriteString("0 0 0 rg\n")

	y := 700
	row := func(label, value string) {
		text("F2", 11, 50, y, label)
		text("F1", 11, 210, y, clean(value, 62))
		line(50, y-9, 545, y-9)
		y -= 30
	}
	row("Property", d.PropertyTitle)
	row("Tenant", d.TenantName)
	row("Landlord", d.OwnerName)
	row("Rent period", d.PeriodLabel)
	row("Due date", d.DueDate)
	row("Paid on", d.PaidDate)
	row("Payment mode", d.Method)
	if d.Reference != "" {
		row("Reference", d.Reference)
	}

	y -= 10
	c.WriteString("0.94 0.96 0.98 rg 50 " + fmt.Sprint(y-92) + " 495 108 re f\n0 0 0 rg\n")
	text("F1", 12, 65, y-8, "Monthly rent")
	text("F1", 12, 400, y-8, money(d.RentAmount))
	lateLabel := "Late fee"
	if d.LateDays > 0 {
		lateLabel = fmt.Sprintf("Late fee (%d days late)", d.LateDays)
	}
	text("F1", 12, 65, y-34, lateLabel)
	text("F1", 12, 400, y-34, money(d.LateFee))
	line(65, y-48, 530, y-48)
	text("F2", 14, 65, y-74, "TOTAL PAID")
	text("F2", 14, 400, y-74, money(d.Total))

	text("F1", 9, 50, 70, "This is a computer-generated receipt and does not need a signature.")
	text("F1", 9, 50, 56, "Generated by PropTech.")

	stream := c.String()
	objs := []string{
		"<< /Type /Catalog /Pages 2 0 R >>",
		"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
		"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R " +
			"/Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>",
		fmt.Sprintf("<< /Length %d >>\nstream\n%sendstream", len(stream), stream),
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
		"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
	}

	var out bytes.Buffer
	out.WriteString("%PDF-1.4\n")
	offsets := make([]int, len(objs))
	for i, o := range objs {
		offsets[i] = out.Len()
		fmt.Fprintf(&out, "%d 0 obj\n%s\nendobj\n", i+1, o)
	}
	xref := out.Len()
	fmt.Fprintf(&out, "xref\n0 %d\n", len(objs)+1)
	out.WriteString("0000000000 65535 f \n")
	for _, off := range offsets {
		fmt.Fprintf(&out, "%010d 00000 n \n", off)
	}
	fmt.Fprintf(&out, "trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n", len(objs)+1, xref)
	return out.Bytes()
}